package gorb

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.26

import (
	"context"
	"fmt"

	"github.com/nibbleshift/gorb/ent"
)

// AllocedBytesPerOp is the resolver for the allocedbytesperop field.
func (r *benchResultResolver) AllocedBytesPerOp(ctx context.Context, obj *ent.BenchResult) (int, error) {
	panic(fmt.Errorf("not implemented"))
}

// AllocsPerOp is the resolver for the allocsperop field.
func (r *benchResultResolver) AllocsPerOp(ctx context.Context, obj *ent.BenchResult) (int, error) {
	panic(fmt.Errorf("not implemented"))
}

// Node is the resolver for the node field.
func (r *queryResolver) Node(ctx context.Context, id int) (ent.Noder, error) {
	panic(fmt.Errorf("not implemented"))
}

// Nodes is the resolver for the nodes field.
func (r *queryResolver) Nodes(ctx context.Context, ids []int) ([]ent.Noder, error) {
	panic(fmt.Errorf("not implemented"))
}

// Benches is the resolver for the benches field.
func (r *queryResolver) Benches(ctx context.Context) ([]*ent.Bench, error) {
	return r.client.Bench.Query().All(ctx)
}

// BenchResult returns BenchResultResolver implementation.
func (r *Resolver) BenchResult() BenchResultResolver { return &benchResultResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type benchResultResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
