package gorb

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.26

import (
	"context"

	"github.com/nibbleshift/gorb/ent"
)

// CreateBenchmark is the resolver for the createBenchmark field.
func (r *mutationResolver) CreateBenchmark(ctx context.Context, input ent.CreateBenchInput) (*ent.Bench, error) {
	return r.client.Bench.Create().SetInput(input).Save(ctx)
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

type mutationResolver struct{ *Resolver }
