# https://taskfile.dev

version: '3'

vars:
  GREETING: Hello, World!

tasks:
  default:
    cmds:
      - task: install-deps
      - task: generate
      - task: build-all
    silent: true
  install-deps:
    - task: install-goreleaser
  install-goreleaser:
    cmds:
      - go install github.com/goreleaser/goreleaser@latest
    status:
      - test -f $(which goreleaser)
  generate:
    cmds:
      - go generate .
  build-gorb:
    cmds:
      - go build -o dist/gorb cmd/gorb/main.go
  build-gorbd:
    cmds:
      - go build -o dist/gorbd cmd/gorbd/main.go
  build-all:
    deps:
      - build-gorb
      - build-gorbd
