package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.26

import (
	"context"

	"github.com/nibbleshift/gorb/ent"
	"github.com/nibbleshift/gorb/graph/generated"
)

// CreateBenchmark is the resolver for the createBenchmark field.
func (r *mutationResolver) CreateBenchmark(ctx context.Context, input ent.CreateBenchInput, results []*ent.CreateBenchResultInput) (*ent.Bench, error) {

	var benchResultIds []int
	for _, r := range results {
		res, err := r.client.BenchResult.Create().SetInput(input).Save(ctx)

		benchResultIds = append(benchResultIds, res.ID)
	}

	input.BenchResult = 

	res, err := r.client.Bench.Create().SetInput(input).Save(ctx)

	return res, err
}

// Mutation returns generated.MutationResolver implementation.
func (r *Resolver) Mutation() generated.MutationResolver { return &mutationResolver{r} }

type mutationResolver struct{ *Resolver }
