// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// BenchesColumns holds the columns for the "benches" table.
	BenchesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
	}
	// BenchesTable holds the schema information for the "benches" table.
	BenchesTable = &schema.Table{
		Name:       "benches",
		Columns:    BenchesColumns,
		PrimaryKey: []*schema.Column{BenchesColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		BenchesTable,
	}
)

func init() {
}
