// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"github.com/99designs/gqlgen/graphql"
)

func (b *Bench) Results(ctx context.Context) (result []*BenchResult, err error) {
	if fc := graphql.GetFieldContext(ctx); fc != nil && fc.Field.Alias != "" {
		result, err = b.NamedResults(graphql.GetFieldContext(ctx).Field.Alias)
	} else {
		result, err = b.Edges.ResultsOrErr()
	}
	if IsNotLoaded(err) {
		result, err = b.QueryResults().All(ctx)
	}
	return result, err
}
