// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"

	"entgo.io/contrib/entgql"
	"entgo.io/ent/dialect/sql"
	"github.com/99designs/gqlgen/graphql"
	"github.com/99designs/gqlgen/graphql/errcode"
	"github.com/nibbleshift/gorb/ent/bench"
	"github.com/nibbleshift/gorb/ent/benchresult"
	"github.com/vektah/gqlparser/v2/gqlerror"
)

// Common entgql types.
type (
	Cursor         = entgql.Cursor[int]
	PageInfo       = entgql.PageInfo[int]
	OrderDirection = entgql.OrderDirection
)

func orderFunc(o OrderDirection, field string) OrderFunc {
	if o == entgql.OrderDirectionDesc {
		return Desc(field)
	}
	return Asc(field)
}

const errInvalidPagination = "INVALID_PAGINATION"

func validateFirstLast(first, last *int) (err *gqlerror.Error) {
	switch {
	case first != nil && last != nil:
		err = &gqlerror.Error{
			Message: "Passing both `first` and `last` to paginate a connection is not supported.",
		}
	case first != nil && *first < 0:
		err = &gqlerror.Error{
			Message: "`first` on a connection cannot be less than zero.",
		}
		errcode.Set(err, errInvalidPagination)
	case last != nil && *last < 0:
		err = &gqlerror.Error{
			Message: "`last` on a connection cannot be less than zero.",
		}
		errcode.Set(err, errInvalidPagination)
	}
	return err
}

func collectedField(ctx context.Context, path ...string) *graphql.CollectedField {
	fc := graphql.GetFieldContext(ctx)
	if fc == nil {
		return nil
	}
	field := fc.Field
	oc := graphql.GetOperationContext(ctx)
walk:
	for _, name := range path {
		for _, f := range graphql.CollectFields(oc, field.Selections, nil) {
			if f.Alias == name {
				field = f
				continue walk
			}
		}
		return nil
	}
	return &field
}

func hasCollectedField(ctx context.Context, path ...string) bool {
	if graphql.GetFieldContext(ctx) == nil {
		return true
	}
	return collectedField(ctx, path...) != nil
}

const (
	edgesField      = "edges"
	nodeField       = "node"
	pageInfoField   = "pageInfo"
	totalCountField = "totalCount"
)

func paginateLimit(first, last *int) int {
	var limit int
	if first != nil {
		limit = *first + 1
	} else if last != nil {
		limit = *last + 1
	}
	return limit
}

// BenchEdge is the edge representation of Bench.
type BenchEdge struct {
	Node   *Bench `json:"node"`
	Cursor Cursor `json:"cursor"`
}

// BenchConnection is the connection containing edges to Bench.
type BenchConnection struct {
	Edges      []*BenchEdge `json:"edges"`
	PageInfo   PageInfo     `json:"pageInfo"`
	TotalCount int          `json:"totalCount"`
}

func (c *BenchConnection) build(nodes []*Bench, pager *benchPager, after *Cursor, first *int, before *Cursor, last *int) {
	c.PageInfo.HasNextPage = before != nil
	c.PageInfo.HasPreviousPage = after != nil
	if first != nil && *first+1 == len(nodes) {
		c.PageInfo.HasNextPage = true
		nodes = nodes[:len(nodes)-1]
	} else if last != nil && *last+1 == len(nodes) {
		c.PageInfo.HasPreviousPage = true
		nodes = nodes[:len(nodes)-1]
	}
	var nodeAt func(int) *Bench
	if last != nil {
		n := len(nodes) - 1
		nodeAt = func(i int) *Bench {
			return nodes[n-i]
		}
	} else {
		nodeAt = func(i int) *Bench {
			return nodes[i]
		}
	}
	c.Edges = make([]*BenchEdge, len(nodes))
	for i := range nodes {
		node := nodeAt(i)
		c.Edges[i] = &BenchEdge{
			Node:   node,
			Cursor: pager.toCursor(node),
		}
	}
	if l := len(c.Edges); l > 0 {
		c.PageInfo.StartCursor = &c.Edges[0].Cursor
		c.PageInfo.EndCursor = &c.Edges[l-1].Cursor
	}
	if c.TotalCount == 0 {
		c.TotalCount = len(nodes)
	}
}

// BenchPaginateOption enables pagination customization.
type BenchPaginateOption func(*benchPager) error

// WithBenchOrder configures pagination ordering.
func WithBenchOrder(order *BenchOrder) BenchPaginateOption {
	if order == nil {
		order = DefaultBenchOrder
	}
	o := *order
	return func(pager *benchPager) error {
		if err := o.Direction.Validate(); err != nil {
			return err
		}
		if o.Field == nil {
			o.Field = DefaultBenchOrder.Field
		}
		pager.order = &o
		return nil
	}
}

// WithBenchFilter configures pagination filter.
func WithBenchFilter(filter func(*BenchQuery) (*BenchQuery, error)) BenchPaginateOption {
	return func(pager *benchPager) error {
		if filter == nil {
			return errors.New("BenchQuery filter cannot be nil")
		}
		pager.filter = filter
		return nil
	}
}

type benchPager struct {
	reverse bool
	order   *BenchOrder
	filter  func(*BenchQuery) (*BenchQuery, error)
}

func newBenchPager(opts []BenchPaginateOption, reverse bool) (*benchPager, error) {
	pager := &benchPager{reverse: reverse}
	for _, opt := range opts {
		if err := opt(pager); err != nil {
			return nil, err
		}
	}
	if pager.order == nil {
		pager.order = DefaultBenchOrder
	}
	return pager, nil
}

func (p *benchPager) applyFilter(query *BenchQuery) (*BenchQuery, error) {
	if p.filter != nil {
		return p.filter(query)
	}
	return query, nil
}

func (p *benchPager) toCursor(b *Bench) Cursor {
	return p.order.Field.toCursor(b)
}

func (p *benchPager) applyCursors(query *BenchQuery, after, before *Cursor) (*BenchQuery, error) {
	direction := p.order.Direction
	if p.reverse {
		direction = direction.Reverse()
	}
	for _, predicate := range entgql.CursorsPredicate(after, before, DefaultBenchOrder.Field.field, p.order.Field.field, direction) {
		query = query.Where(predicate)
	}
	return query, nil
}

func (p *benchPager) applyOrder(query *BenchQuery) *BenchQuery {
	direction := p.order.Direction
	if p.reverse {
		direction = direction.Reverse()
	}
	query = query.Order(orderFunc(direction, p.order.Field.field))
	if p.order.Field != DefaultBenchOrder.Field {
		query = query.Order(orderFunc(direction, DefaultBenchOrder.Field.field))
	}
	return query
}

func (p *benchPager) orderExpr() sql.Querier {
	direction := p.order.Direction
	if p.reverse {
		direction = direction.Reverse()
	}
	return sql.ExprFunc(func(b *sql.Builder) {
		b.Ident(p.order.Field.field).Pad().WriteString(string(direction))
		if p.order.Field != DefaultBenchOrder.Field {
			b.Comma().Ident(DefaultBenchOrder.Field.field).Pad().WriteString(string(direction))
		}
	})
}

// Paginate executes the query and returns a relay based cursor connection to Bench.
func (b *BenchQuery) Paginate(
	ctx context.Context, after *Cursor, first *int,
	before *Cursor, last *int, opts ...BenchPaginateOption,
) (*BenchConnection, error) {
	if err := validateFirstLast(first, last); err != nil {
		return nil, err
	}
	pager, err := newBenchPager(opts, last != nil)
	if err != nil {
		return nil, err
	}
	if b, err = pager.applyFilter(b); err != nil {
		return nil, err
	}
	conn := &BenchConnection{Edges: []*BenchEdge{}}
	ignoredEdges := !hasCollectedField(ctx, edgesField)
	if hasCollectedField(ctx, totalCountField) || hasCollectedField(ctx, pageInfoField) {
		hasPagination := after != nil || first != nil || before != nil || last != nil
		if hasPagination || ignoredEdges {
			if conn.TotalCount, err = b.Clone().Count(ctx); err != nil {
				return nil, err
			}
			conn.PageInfo.HasNextPage = first != nil && conn.TotalCount > 0
			conn.PageInfo.HasPreviousPage = last != nil && conn.TotalCount > 0
		}
	}
	if ignoredEdges || (first != nil && *first == 0) || (last != nil && *last == 0) {
		return conn, nil
	}

	if b, err = pager.applyCursors(b, after, before); err != nil {
		return nil, err
	}
	b = pager.applyOrder(b)
	if limit := paginateLimit(first, last); limit != 0 {
		b.Limit(limit)
	}
	if field := collectedField(ctx, edgesField, nodeField); field != nil {
		if err := b.collectField(ctx, graphql.GetOperationContext(ctx), *field, []string{edgesField, nodeField}); err != nil {
			return nil, err
		}
	}

	nodes, err := b.All(ctx)
	if err != nil {
		return nil, err
	}
	conn.build(nodes, pager, after, first, before, last)
	return conn, nil
}

// BenchOrderField defines the ordering field of Bench.
type BenchOrderField struct {
	field    string
	toCursor func(*Bench) Cursor
}

// BenchOrder defines the ordering of Bench.
type BenchOrder struct {
	Direction OrderDirection   `json:"direction"`
	Field     *BenchOrderField `json:"field"`
}

// DefaultBenchOrder is the default ordering of Bench.
var DefaultBenchOrder = &BenchOrder{
	Direction: entgql.OrderDirectionAsc,
	Field: &BenchOrderField{
		field: bench.FieldID,
		toCursor: func(b *Bench) Cursor {
			return Cursor{ID: b.ID}
		},
	},
}

// ToEdge converts Bench into BenchEdge.
func (b *Bench) ToEdge(order *BenchOrder) *BenchEdge {
	if order == nil {
		order = DefaultBenchOrder
	}
	return &BenchEdge{
		Node:   b,
		Cursor: order.Field.toCursor(b),
	}
}

// BenchResultEdge is the edge representation of BenchResult.
type BenchResultEdge struct {
	Node   *BenchResult `json:"node"`
	Cursor Cursor       `json:"cursor"`
}

// BenchResultConnection is the connection containing edges to BenchResult.
type BenchResultConnection struct {
	Edges      []*BenchResultEdge `json:"edges"`
	PageInfo   PageInfo           `json:"pageInfo"`
	TotalCount int                `json:"totalCount"`
}

func (c *BenchResultConnection) build(nodes []*BenchResult, pager *benchresultPager, after *Cursor, first *int, before *Cursor, last *int) {
	c.PageInfo.HasNextPage = before != nil
	c.PageInfo.HasPreviousPage = after != nil
	if first != nil && *first+1 == len(nodes) {
		c.PageInfo.HasNextPage = true
		nodes = nodes[:len(nodes)-1]
	} else if last != nil && *last+1 == len(nodes) {
		c.PageInfo.HasPreviousPage = true
		nodes = nodes[:len(nodes)-1]
	}
	var nodeAt func(int) *BenchResult
	if last != nil {
		n := len(nodes) - 1
		nodeAt = func(i int) *BenchResult {
			return nodes[n-i]
		}
	} else {
		nodeAt = func(i int) *BenchResult {
			return nodes[i]
		}
	}
	c.Edges = make([]*BenchResultEdge, len(nodes))
	for i := range nodes {
		node := nodeAt(i)
		c.Edges[i] = &BenchResultEdge{
			Node:   node,
			Cursor: pager.toCursor(node),
		}
	}
	if l := len(c.Edges); l > 0 {
		c.PageInfo.StartCursor = &c.Edges[0].Cursor
		c.PageInfo.EndCursor = &c.Edges[l-1].Cursor
	}
	if c.TotalCount == 0 {
		c.TotalCount = len(nodes)
	}
}

// BenchResultPaginateOption enables pagination customization.
type BenchResultPaginateOption func(*benchresultPager) error

// WithBenchResultOrder configures pagination ordering.
func WithBenchResultOrder(order *BenchResultOrder) BenchResultPaginateOption {
	if order == nil {
		order = DefaultBenchResultOrder
	}
	o := *order
	return func(pager *benchresultPager) error {
		if err := o.Direction.Validate(); err != nil {
			return err
		}
		if o.Field == nil {
			o.Field = DefaultBenchResultOrder.Field
		}
		pager.order = &o
		return nil
	}
}

// WithBenchResultFilter configures pagination filter.
func WithBenchResultFilter(filter func(*BenchResultQuery) (*BenchResultQuery, error)) BenchResultPaginateOption {
	return func(pager *benchresultPager) error {
		if filter == nil {
			return errors.New("BenchResultQuery filter cannot be nil")
		}
		pager.filter = filter
		return nil
	}
}

type benchresultPager struct {
	reverse bool
	order   *BenchResultOrder
	filter  func(*BenchResultQuery) (*BenchResultQuery, error)
}

func newBenchResultPager(opts []BenchResultPaginateOption, reverse bool) (*benchresultPager, error) {
	pager := &benchresultPager{reverse: reverse}
	for _, opt := range opts {
		if err := opt(pager); err != nil {
			return nil, err
		}
	}
	if pager.order == nil {
		pager.order = DefaultBenchResultOrder
	}
	return pager, nil
}

func (p *benchresultPager) applyFilter(query *BenchResultQuery) (*BenchResultQuery, error) {
	if p.filter != nil {
		return p.filter(query)
	}
	return query, nil
}

func (p *benchresultPager) toCursor(br *BenchResult) Cursor {
	return p.order.Field.toCursor(br)
}

func (p *benchresultPager) applyCursors(query *BenchResultQuery, after, before *Cursor) (*BenchResultQuery, error) {
	direction := p.order.Direction
	if p.reverse {
		direction = direction.Reverse()
	}
	for _, predicate := range entgql.CursorsPredicate(after, before, DefaultBenchResultOrder.Field.field, p.order.Field.field, direction) {
		query = query.Where(predicate)
	}
	return query, nil
}

func (p *benchresultPager) applyOrder(query *BenchResultQuery) *BenchResultQuery {
	direction := p.order.Direction
	if p.reverse {
		direction = direction.Reverse()
	}
	query = query.Order(orderFunc(direction, p.order.Field.field))
	if p.order.Field != DefaultBenchResultOrder.Field {
		query = query.Order(orderFunc(direction, DefaultBenchResultOrder.Field.field))
	}
	return query
}

func (p *benchresultPager) orderExpr() sql.Querier {
	direction := p.order.Direction
	if p.reverse {
		direction = direction.Reverse()
	}
	return sql.ExprFunc(func(b *sql.Builder) {
		b.Ident(p.order.Field.field).Pad().WriteString(string(direction))
		if p.order.Field != DefaultBenchResultOrder.Field {
			b.Comma().Ident(DefaultBenchResultOrder.Field.field).Pad().WriteString(string(direction))
		}
	})
}

// Paginate executes the query and returns a relay based cursor connection to BenchResult.
func (br *BenchResultQuery) Paginate(
	ctx context.Context, after *Cursor, first *int,
	before *Cursor, last *int, opts ...BenchResultPaginateOption,
) (*BenchResultConnection, error) {
	if err := validateFirstLast(first, last); err != nil {
		return nil, err
	}
	pager, err := newBenchResultPager(opts, last != nil)
	if err != nil {
		return nil, err
	}
	if br, err = pager.applyFilter(br); err != nil {
		return nil, err
	}
	conn := &BenchResultConnection{Edges: []*BenchResultEdge{}}
	ignoredEdges := !hasCollectedField(ctx, edgesField)
	if hasCollectedField(ctx, totalCountField) || hasCollectedField(ctx, pageInfoField) {
		hasPagination := after != nil || first != nil || before != nil || last != nil
		if hasPagination || ignoredEdges {
			if conn.TotalCount, err = br.Clone().Count(ctx); err != nil {
				return nil, err
			}
			conn.PageInfo.HasNextPage = first != nil && conn.TotalCount > 0
			conn.PageInfo.HasPreviousPage = last != nil && conn.TotalCount > 0
		}
	}
	if ignoredEdges || (first != nil && *first == 0) || (last != nil && *last == 0) {
		return conn, nil
	}

	if br, err = pager.applyCursors(br, after, before); err != nil {
		return nil, err
	}
	br = pager.applyOrder(br)
	if limit := paginateLimit(first, last); limit != 0 {
		br.Limit(limit)
	}
	if field := collectedField(ctx, edgesField, nodeField); field != nil {
		if err := br.collectField(ctx, graphql.GetOperationContext(ctx), *field, []string{edgesField, nodeField}); err != nil {
			return nil, err
		}
	}

	nodes, err := br.All(ctx)
	if err != nil {
		return nil, err
	}
	conn.build(nodes, pager, after, first, before, last)
	return conn, nil
}

// BenchResultOrderField defines the ordering field of BenchResult.
type BenchResultOrderField struct {
	field    string
	toCursor func(*BenchResult) Cursor
}

// BenchResultOrder defines the ordering of BenchResult.
type BenchResultOrder struct {
	Direction OrderDirection         `json:"direction"`
	Field     *BenchResultOrderField `json:"field"`
}

// DefaultBenchResultOrder is the default ordering of BenchResult.
var DefaultBenchResultOrder = &BenchResultOrder{
	Direction: entgql.OrderDirectionAsc,
	Field: &BenchResultOrderField{
		field: benchresult.FieldID,
		toCursor: func(br *BenchResult) Cursor {
			return Cursor{ID: br.ID}
		},
	},
}

// ToEdge converts BenchResult into BenchResultEdge.
func (br *BenchResult) ToEdge(order *BenchResultOrder) *BenchResultEdge {
	if order == nil {
		order = DefaultBenchResultOrder
	}
	return &BenchResultEdge{
		Node:   br,
		Cursor: order.Field.toCursor(br),
	}
}
