// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Bench is the predicate function for bench builders.
type Bench func(*sql.Selector)

// BenchResult is the predicate function for benchresult builders.
type BenchResult func(*sql.Selector)
